Reworked verify workflow using native features

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -7,60 +7,43 @@ jobs:
     name: Verify
     runs-on: ubuntu-latest
 
-    env:
-      failed: "false"
-
     steps:
       - uses: actions/checkout@main
       - uses: cachix/install-nix-action@master
 
       - name: Check
-        continue-on-error: true
+        if: ${{ !cancelled() }}
         run: |
           sudo mkdir -p /etc/nixos
           echo '{ nixpkgs.hostPlatform = "x86_64-linux"; }' | sudo tee /etc/nixos/hardware.nix > /dev/null
 
-          _failed="false"
-          nix flake check --impure --option keep-going true || _failed="true"
-
-          if [ "$_failed" = "true" ]; then
-            echo "failed=true" >> "$GITHUB_ENV"
-            exit 1
-          fi
+          failed="false"
+          nix flake check --impure --option keep-going true || failed="true"
+          test "$failed" = "false"
 
       - name: Lint Nix
-        continue-on-error: true
+        if: ${{ !cancelled() }}
         run: |
-          _failed="false"
+          failed="false"
           find . -name "*.nix" | while read -r file; do
             echo "Checking $file"
             diagnostics="$(nix run nixpkgs#nil -- diagnostics "$file")"
 
             if [ -n "$diagnostics" ]; then
               echo "$diagnostics"
-              _failed="true"
+              failed="true"
             fi
           done
 
-          if [ "$_failed" = "true" ]; then
-            echo "failed=true" >> "$GITHUB_ENV"
-            exit 1
-          fi
+          test "$failed" = "false"
 
       - name: Lint Shell
-        continue-on-error: true
+        if: ${{ !cancelled() }}
         run: |
-          _failed="false"
+          failed="false"
           find . -name "*.sh" | while read -r file; do
             echo "Checking $file"
-            nix run nixpkgs#shellcheck -- "$file" || _failed="true"
+            nix run nixpkgs#shellcheck -- "$file" || failed="true"
           done
 
-          if [ "$_failed" = "true" ]; then
-            echo "failed=true" >> "$GITHUB_ENV"
-            exit 1
-          fi
-
-      - name: Fail
-        if: env.failed == 'true'
-        run: exit 1
+          test "$failed" = "false"
