Added statix to verify workflow

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -17,14 +17,14 @@ jobs:
           sudo mkdir -p /etc/nixos
           echo '{ nixpkgs.hostPlatform = "x86_64-linux"; }' | sudo tee /etc/nixos/hardware.nix > /dev/null
 
-          failed="false"
-          nix flake check --impure --option keep-going true || failed="true"
-          test "$failed" = "false"
+          nix flake check --impure --option keep-going true
 
       - name: Lint Nix
         if: ${{ !cancelled() }}
         run: |
           failed="false"
+          nix run nixpkgs#statix check || failed="true"
+
           find . -name "*.nix" | while read -r file; do
             echo "Checking $file"
             diagnostics="$(nix run nixpkgs#nil -- diagnostics "$file")"
